export const Constants ={
    companyId:2,
    token:'eyJDb21wYW55SWQiOjIsIlJlZ2lzdHJhdGlvbklkIjo4LCJSZWdpc3RyYXRpb25UeXBlSWQiOjEsIlJlZ2lzdHJhdGlvblR5cGVOYW1lIjoiQ29tcGFueSIsIlJlZ2lzdGVyTW9iaWxlTnVtYmVyIjoiNjMwMjk3NTM4MyIsIlJlZ2lzdGVyTmFtZSI6IlNoaXZhIEt1bWFyIiwiSXNBY3RpdmUiOnRydWV9'
  }